services:
    geogenie:
        container_name: geogenie-backend
        # Use 'vijethegde/geogenie:latest' for x86_64 (Linux Laptop/Desktop)
        # Use 'vijethegde/geogenie:pi' for ARM64 (Raspberry Pi 5)
        image: vijethegde/geogenie:pi
        env_file: .env
        ports:
            - "9000:8000"
        volumes:
            - ./landmarks:/app/landmarks
            - ./data:/app/data
        restart: unless-stopped
