services:
    geogenie:
        container_name: geogenie-backend
        image: vijethegde/geogenie:latest
        env_file: .env
        ports:
            - "9000:8000"
        volumes:
            - ./landmarks:/app/landmarks
            - ./data:/app/data
        restart: unless-stopped
